/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_netease_mc_mod_network_common_Library */

#ifndef _Included_com_netease_mc_mod_network_common_Library
#define _Included_com_netease_mc_mod_network_common_Library
#ifdef __cplusplus
extern "C" {
#endif
#undef com_netease_mc_mod_network_common_Library_REVIEW_FAILED
#define com_netease_mc_mod_network_common_Library_REVIEW_FAILED 2L
/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    DecryptClassBytes
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_netease_mc_mod_network_common_Library_DecryptClassBytes
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    GetToken
 * Signature: ([BI)V
 */
JNIEXPORT void JNICALL Java_com_netease_mc_mod_network_common_Library_GetToken
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    NewChaCha
 * Signature: (I[B)J
 */
JNIEXPORT jlong JNICALL Java_com_netease_mc_mod_network_common_Library_NewChaCha
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    DeleteChaCha
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_netease_mc_mod_network_common_Library_DeleteChaCha
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    ChaChaProcess
 * Signature: (J[BI)V
 */
JNIEXPORT void JNICALL Java_com_netease_mc_mod_network_common_Library_ChaChaProcess
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    Skip32
 * Signature: (Z[BI)I
 */
JNIEXPORT jint JNICALL Java_com_netease_mc_mod_network_common_Library_Skip32
  (JNIEnv *, jclass, jboolean, jbyteArray, jint);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_netease_mc_mod_network_common_Library_init
  (JNIEnv *, jclass);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    preInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_netease_mc_mod_network_common_Library_preInit
  (JNIEnv *, jclass);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    log
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_netease_mc_mod_network_common_Library_log
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_netease_mc_mod_network_common_Library_close
  (JNIEnv *, jclass);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_netease_mc_mod_network_common_Library_test
  (JNIEnv *, jclass);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    reviewName
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_netease_mc_mod_network_common_Library_reviewName
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_netease_mc_mod_network_common_Library
 * Method:    reviewWord
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_netease_mc_mod_network_common_Library_reviewWord
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
